name: llmops
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    volumes:
    - ../litellm/config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--debug"]
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://llmops:llmops@db:5432/litellm"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - llmops-network

  routing_redis:
    image: docker.io/redis:7
    container_name: routing_redis
    ports:
      - "8003:8001"  # RedisInsight Web UI
    restart: always
    networks:
      - llmops-network

networks:
  llmops-network:
    name: llmops-network
    driver: bridge
